import { useState, useEffect, useCallback } from "react";
import { useRouter } from "next/router";
import toast from "react-hot-toast";
import Head from "next/head";
import axios from "axios";

import LoadingOverlay from "../../../components/LoadingOverlay";

export default function DeleteNote({ token }) {
  const router = useRouter();

  const { id } = router.query;

  const [isLoading, setLoadingStatus] = useState(true);
  const [title, setTitle] = useState("");

  const submitCallback = useCallback(() => {
    setLoadingStatus(true);
    toast.loading("Deleting the note...", { id: "deleteNote" });

    axios
      .delete(`${process.env.API_URL}/notes/${id}`, {
        headers: { Authorization: token },
      })
      .then((resp) => {
        toast.success("Successfully deleted the note!", { id: "deleteNote" });
        router.push("/dashboard");
      })
      .catch((err) => {
        let message;

        switch (err.response.status) {
          case 404:
            message = "note does not exist or inaccessible";
            router.push("/dashboard");
            break;

          case 401:
            message = "invalid session";
            setToken("");
            break;

          default:
            message = "unknown error";
        }

        toast.error(`Failed to delete the note: ${message}`, {
          id: "deleteNote",
        });
      })
      .finally(() => {
        setLoadingStatus(false);
      });
  }, [id, title]);

  useEffect(() => {
    if (!token) router.push("/");
  }, [token]);

  useEffect(() => {
    if (token) {
      axios
        .get(`${process.env.API_URL}/notes/${id}`, {
          headers: { Authorization: token },
        })
        .then((resp) => {
          setTitle(resp.data.title);
          setLoadingStatus(false);
        })
        .catch((err) => {
          let message;

          switch (err.response.status) {
            case 404:
              message = "note does not exist or inaccessible";
              router.push("/dashboard");
              break;

            case 401:
              message = "invalid session";
              setToken("");
              break;

            default:
              message = "unknown error";
          }

          toast.error(`Something went wrong: ${message}`, {
            id: "deleteNote",
          });
        });
    }
  }, [token]);

  return (
    <>
      <Head>
        <title>Delete note | Journal App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LoadingOverlay isLoading={isLoading} />
      <div className="min-vh-100 d-flex flex-column bg-light">
        <main className="container px-3 py-5 mt-auto">
          <div className="row g-4">
            <div className="col-12 d-flex flex-column align-items-center justify-content-center">
              <div className="card p-3 w-100" style={{ maxWidth: "900px" }}>
                <div className="card-body container">
                  <div className="row g-3">
                    <div className="col">
                      <h2 className="card-title m-0">Delete Note</h2>
                    </div>
                  </div>
                  <hr />
                  <p>Are you sure you want to delete this note?</p>
                  <p>
                    <strong>Note title: </strong>
                    <em>"{title}"</em>
                  </p>
                  <button
                    type="button"
                    className="btn btn-danger"
                    onClick={submitCallback}
                  >
                    Confirm
                  </button>
                </div>
              </div>
            </div>
          </div>
        </main>
        <footer className="mt-auto">
          <p className="text-center">
            © 2021 Alvito Raidhy Trinanda. MIT Licensed.
          </p>
        </footer>
      </div>
    </>
  );
}
